### ISSUE TITLE
Evaluating MultiPoint

### ISSUE THREAD

**Issue by eminerkol-60** [ethz-asl/multipoint#4]
Hi, When you are evaluating MultiPoint model, which method are you using for exporting the key points? Is it again SURF, like you use in training?

**Comment by acfloria** [comment]
Hi,

Multipoint is like SURF a keypoint detector **and** descriptor.
The output of Multipoint is for every pixel in the image on one hand a heatmap of keypoint probabilities and a descriptor for every pixel. With NMS and a threshold we get keypoint locations from the heatmap and then extract the descriptors at the keypoint locations.
I hope this answers your questions.

**Comment by eminerkol-60** [comment]
Yes, thanks for the fast reply.
