### ISSUE TITLE
retraining(fine tuning)  the model

### ISSUE THREAD

**Issue by MohamedElsaeidy** [ethz-asl/multipoint#5]
hello, i am trying to retrain the model with different image size as 512x512 using  flag -w multipoint latest model but i got  runtime error loading state_dict for MultiPoint:
i could avoid it with ignoring the errors but in testing i got 0 keypoints
<pre>    net.load_state_dict(weights)
  File &quot;/home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py&quot;, line 1483, in load_state_dict
    self.__class__.__name__, &quot;\n\t&quot;.join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiPoint:
	Missing key(s) in state_dict: &quot;encoder.1.weight&quot;, &quot;encoder.1.bias&quot;, &quot;encoder.3.weight&quot;, &quot;encoder.3.bias&quot;, &quot;encoder.3.running_mean&quot;, &quot;encoder.3.running_var&quot;, &quot;encoder.5.weight&quot;, &quot;encoder.5.bias&quot;, &quot;encoder.7.weight&quot;, &quot;encoder.7.bias&quot;, &quot;encoder.7.running_mean&quot;, &quot;encoder.7.running_var&quot;, &quot;encoder.10.weight&quot;, &quot;encoder.10.bias&quot;, &quot;encoder.12.weight&quot;, &quot;encoder.12.bias&quot;, &quot;encoder.12.running_mean&quot;, &quot;encoder.12.running_var&quot;, &quot;encoder.14.weight&quot;, &quot;encoder.14.bias&quot;, &quot;encoder.16.weight&quot;, &quot;encoder.16.bias&quot;, &quot;encoder.16.running_mean&quot;, &quot;encoder.16.running_var&quot;, &quot;encoder.19.weight&quot;, &quot;encoder.19.bias&quot;, &quot;encoder.21.weight&quot;, &quot;encoder.21.bias&quot;, &quot;encoder.21.running_mean&quot;, &quot;encoder.21.running_var&quot;, &quot;encoder.23.weight&quot;, &quot;encoder.23.bias&quot;, &quot;encoder.25.weight&quot;, &quot;encoder.25.bias&quot;, &quot;encoder.25.running_mean&quot;, &quot;encoder.25.running_var&quot;, &quot;encoder.28.weight&quot;, &quot;encoder.28.bias&quot;, &quot;encoder.30.weight&quot;, &quot;encoder.30.bias&quot;, &quot;encoder.30.running_mean&quot;, &quot;encoder.30.running_var&quot;, &quot;encoder.32.weight&quot;, &quot;encoder.32.bias&quot;, &quot;encoder.34.weight&quot;, &quot;encoder.34.bias&quot;, &quot;encoder.34.running_mean&quot;, &quot;encoder.34.running_var&quot;. 
	Unexpected key(s) in state_dict: &quot;encoder_thermal.1.weight&quot;, &quot;encoder_thermal.1.bias&quot;, &quot;encoder_thermal.3.weight&quot;, &quot;encoder_thermal.3.bias&quot;, &quot;encoder_thermal.3.running_mean&quot;, &quot;encoder_thermal.3.running_var&quot;, &quot;encoder_thermal.3.num_batches_tracked&quot;, &quot;encoder_thermal.5.weight&quot;, &quot;encoder_thermal.5.bias&quot;, &quot;encoder_thermal.7.weight&quot;, &quot;encoder_thermal.7.bias&quot;, &quot;encoder_thermal.7.running_mean&quot;, &quot;encoder_thermal.7.running_var&quot;, &quot;encoder_thermal.7.num_batches_tracked&quot;, &quot;encoder_thermal.10.weight&quot;, &quot;encoder_thermal.10.bias&quot;, &quot;encoder_thermal.12.weight&quot;, &quot;encoder_thermal.12.bias&quot;, &quot;encoder_thermal.12.running_mean&quot;, &quot;encoder_thermal.12.running_var&quot;, &quot;encoder_thermal.12.num_batches_tracked&quot;, &quot;encoder_thermal.14.weight&quot;, &quot;encoder_thermal.14.bias&quot;, &quot;encoder_thermal.16.weight&quot;, &quot;encoder_thermal.16.bias&quot;, &quot;encoder_thermal.16.running_mean&quot;, &quot;encoder_thermal.16.running_var&quot;, &quot;encoder_thermal.16.num_batches_tracked&quot;, &quot;encoder_thermal.19.weight&quot;, &quot;encoder_thermal.19.bias&quot;, &quot;encoder_thermal.21.weight&quot;, &quot;encoder_thermal.21.bias&quot;, &quot;encoder_thermal.21.running_mean&quot;, &quot;encoder_thermal.21.running_var&quot;, &quot;encoder_thermal.21.num_batches_tracked&quot;, &quot;encoder_thermal.23.weight&quot;, &quot;encoder_thermal.23.bias&quot;, &quot;encoder_thermal.25.weight&quot;, &quot;encoder_thermal.25.bias&quot;, &quot;encoder_thermal.25.running_mean&quot;, &quot;encoder_thermal.25.running_var&quot;, &quot;encoder_thermal.25.num_batches_tracked&quot;, &quot;encoder_thermal.28.weight&quot;, &quot;encoder_thermal.28.bias&quot;, &quot;encoder_thermal.30.weight&quot;, &quot;encoder_thermal.30.bias&quot;, &quot;encoder_thermal.30.running_mean&quot;, &quot;encoder_thermal.30.running_var&quot;, &quot;encoder_thermal.30.num_batches_tracked&quot;, &quot;encoder_thermal.32.weight&quot;, &quot;encoder_thermal.32.bias&quot;, &quot;encoder_thermal.34.weight&quot;, &quot;encoder_thermal.34.bias&quot;, &quot;encoder_thermal.34.running_mean&quot;, &quot;encoder_thermal.34.running_var&quot;, &quot;encoder_thermal.34.num_batches_tracked&quot;, &quot;encoder_optical.1.weight&quot;, &quot;encoder_optical.1.bias&quot;, &quot;encoder_optical.3.weight&quot;, &quot;encoder_optical.3.bias&quot;, &quot;encoder_optical.3.running_mean&quot;, &quot;encoder_optical.3.running_var&quot;, &quot;encoder_optical.3.num_batches_tracked&quot;, &quot;encoder_optical.5.weight&quot;, &quot;encoder_optical.5.bias&quot;, &quot;encoder_optical.7.weight&quot;, &quot;encoder_optical.7.bias&quot;, &quot;encoder_optical.7.running_mean&quot;, &quot;encoder_optical.7.running_var&quot;, &quot;encoder_optical.7.num_batches_tracked&quot;, &quot;encoder_optical.10.weight&quot;, &quot;encoder_optical.10.bias&quot;, &quot;encoder_optical.12.weight&quot;, &quot;encoder_optical.12.bias&quot;, &quot;encoder_optical.12.running_mean&quot;, &quot;encoder_optical.12.running_var&quot;, &quot;encoder_optical.12.num_batches_tracked&quot;, &quot;encoder_optical.14.weight&quot;, &quot;encoder_optical.14.bias&quot;, &quot;encoder_optical.16.weight&quot;, &quot;encoder_optical.16.bias&quot;, &quot;encoder_optical.16.running_mean&quot;, &quot;encoder_optical.16.running_var&quot;, &quot;encoder_optical.16.num_batches_tracked&quot;, &quot;encoder_optical.19.weight&quot;, &quot;encoder_optical.19.bias&quot;, &quot;encoder_optical.21.weight&quot;, &quot;encoder_optical.21.bias&quot;, &quot;encoder_optical.21.running_mean&quot;, &quot;encoder_optical.21.running_var&quot;, &quot;encoder_optical.21.num_batches_tracked&quot;, &quot;encoder_optical.23.weight&quot;, &quot;encoder_optical.23.bias&quot;, &quot;encoder_optical.25.weight&quot;, &quot;encoder_optical.25.bias&quot;, &quot;encoder_optical.25.running_mean&quot;, &quot;encoder_optical.25.running_var&quot;, &quot;encoder_optical.25.num_batches_tracked&quot;, &quot;encoder_optical.28.weight&quot;, &quot;encoder_optical.28.bias&quot;, &quot;encoder_optical.30.weight&quot;, &quot;encoder_optical.30.bias&quot;, &quot;encoder_optical.30.running_mean&quot;, &quot;encoder_optical.30.running_var&quot;, &quot;encoder_optical.30.num_batches_tracked&quot;, &quot;encoder_optical.32.weight&quot;, &quot;encoder_optical.32.bias&quot;, &quot;encoder_optical.34.weight&quot;, &quot;encoder_optical.34.bias&quot;, &quot;encoder_optical.34.running_mean&quot;, &quot;encoder_optical.34.running_var&quot;, &quot;encoder_optical.34.num_batches_tracked&quot;. 
	size mismatch for descriptor_head_convolutions.4.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
	size mismatch for descriptor_head_convolutions.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for descriptor_head_convolutions.5.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for descriptor_head_convolutions.5.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for descriptor_head_convolutions.5.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for descriptor_head_convolutions.5.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).</pre>

**Comment by acfloria** [comment]
Hi,

The pretrained weights for the MuliPoint model have a descriptor size of 64. It seems to me the config file you are using specify a descriptor size of 256, which causes loading the weights to fail.
When using the pretrained weights you should use the config file, or at least the values from the model yaml (https://github.com/ethz-asl/multipoint/blob/main/model_weights/multipoint/params.yaml).

**Comment by MohamedElsaeidy** [comment]
can you share the config file you used for training since I tried training with the same model config in multipoint model yaml file but I got 0 key points on exporting and predicting? and defaults in config training yaml seem to be different from your trained model so I can make sure everything is the same.

**Comment by acfloria** [comment]
I updated the config file in the main branch. I tried and it should work with the config file to retrain the pretrained multipoint model.
