### ISSUE TITLE
Compute Detector Metric

### ISSUE THREAD

**Issue by MohamedElsaeidy** [ethz-asl/multipoint#8]
i want to compute TP and FP rates with compute_tp_fp_dist() and to use the function i had set dataset mode to single_image: true

it produces error 

<pre>  File &quot;predict_keypoints.py&quot;, line 287, in &lt;module&gt;
    main()
  File &quot;predict_keypoints.py&quot;, line 97, in main
    config[&apos;prediction&apos;])
  File &quot;/multipoint/utils/evaluation.py&quot;, line 27, in compute_detector_metrics
    out = list(map(lambda p, k: compute_tp_fp_dist(p,k), pred.squeeze().cpu(), data[&apos;keypoints&apos;].cpu()))
  File &quot;/multipoint/multipoint/utils/evaluation.py&quot;, line 27, in &lt;lambda&gt;
    out = list(map(lambda p, k: compute_tp_fp_dist(p,k), pred.squeeze().cpu(), data[&apos;keypoints&apos;].cpu()))
  File &quot;/multipoint/multipoint/utils/evaluation.py&quot;, line 64, in compute_tp_fp_dist
    keypoints = generate_keypoint_map(keypoints, prob.shape)
  File &quot;/multipoint/multipoint/utils/utils.py&quot;, line 65, in generate_keypoint_map
    tmp = keypoints.astype(np.int64)
AttributeError: &apos;Tensor&apos; object has no attribute &apos;astype&apos;</pre>
i check the variables going into that function so printed keypoints.shape and image_shape and he is the output
<pre>(0, 2)
(0, 2)
(0, 2)
(0, 2)
(0, 2)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
(0, 2)
(512, 512)
torch.Size([512, 512])
torch.Size([512])
</pre>
so at somepoint it receives tensor instead of (0,2) metric. i set condition so that if it receives tensor it converts it to np.int64 
then at same point i got this error
<pre>/multipoint/multipoint/utils/utils.py&quot;, line 68, in generate_keypoint_map
    keypoint_map[tmp[:,0],tmp[:,1]] = True
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
</pre>
so can you suggest a way or a fix to calculate TP and FP rates 
one more thing when i disable single_image. the code goes into the same function of generate_keypoint_map()
but i cannot see it anywhere in the code sequence of computing repeatability. and i don't get error from it.

**Comment by acfloria** [comment]
I guess you did the evaluation with a batch size of 1, right?

I just discovered a bug in the code and fixed it in a branch: https://github.com/ethz-asl/multipoint/tree/fix/single_batch_evaluation.

Can you test if this branch fixes your issue?

**Comment by MohamedElsaeidy** [comment]
yes i was using batch size of 1. also i tried now the change for pred[:,0] as you did and tried with batch size 1 and 2 and original code with batch size 2, but all gave same result 0
<pre>predict_keypoints.py:107: RuntimeWarning: Mean of empty slice.
  print(&apos;Average distance error for true positives: {}&apos;.format(dist.mean()))
/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Average distance error for true positives: nan
mAP: 0.0
</pre>

**Comment by acfloria** [comment]
Hmm, then it might be something with the labels/data that you use. For example I am not sure if the current script works if for one sample you don't have any label or the model does not predict any keypoint.

**Comment by MohamedElsaeidy** [comment]
fixed the issue thanks, also for labels it tends to be if i used 1 homography to generate labels it give 0.00 mAP, if i used more homographies the mAP increases. so is it possible to generate labels without homographies because in code it not allowed to use 0 num of homographies. and i am evaluating without homographic adaptation, also when generating i tried to make zero values of homographic adaptation parameters but it was the same.
